<?php

namespace Database\Seeders;

use App\Models\Network;
use Illuminate\Database\Seeder;

class NetworksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $networks = [
            [
                'name' => 'boostiny',
                'display_name' => 'Boostiny Network',
                'description' => 'Leading performance marketing network specializing in mobile apps and e-commerce.',
                'logo_url' => '/images/networks/boostiny-logo.png',
                'api_url' => 'https://api.boostiny.com',
                'auth_url' => 'https://app.boostiny.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/boostiny',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 30,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['campaigns', 'link_performance', 'publisher_performance', 'reports'],
            ],
            [
                'name' => 'digizag',
                'display_name' => 'Digizag Network',
                'description' => 'Performance marketing network powered by HasOffers platform.',
                'logo_url' => '/images/networks/digizag-logo.png',
                'api_url' => 'https://digizag.api.hasoffers.com/Apiv3/json?Target=Affiliate_Report&Method=getConversions&page=1&limit=2000000&fields[]=Stat.offer_id&fields[]=Stat.datetime&fields[]=Offer.name&fields[]=Stat.conversion_status&fields[]=Stat.payout&fields[]=Stat.ad_id&fields[]=Stat.affiliate_info1&fields[]=Stat.affiliate_info5&sort[Stat.datetime]=desc&filters[Stat.date][conditional]=BETWEEN&hour_offset=5&fields[]=Stat.conversion_sale_amount&',
                'auth_url' => 'https://digizag.api.hasoffers.com',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['conversions', 'offers', 'stats', 'reports'],
            ],
            [
                'name' => 'platformance',
                'display_name' => 'Platformance Network',
                'description' => 'Performance marketing platform with advanced tracking and reporting.',
                'logo_url' => '/images/networks/platformance-logo.png',
                'api_url' => 'https://login.platformance.co/publisher/performance.html',
                'auth_url' => 'https://login.platformance.co/login.html',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['performance', 'campaigns', 'coupons', 'reports'],
            ],
            [
                'name' => 'optimisemedia',
                'display_name' => 'OptimiseMedia Network',
                'description' => 'OptimiseMedia affiliate network with comprehensive API reporting and multi-currency support.',
                'logo_url' => 'https://www.optimisemedia.com/assets/icons/logo-circle.svg',
                'api_url' => 'https://public.api.optimisemedia.com/v1/reporting/',
                'auth_url' => 'https://public.api.optimisemedia.com/v1/',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 30,
                    'retry_attempts' => 3,
                    'target_currency' => 'USD',
                    'date_type' => 'conversionDate',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['campaigns', 'coupons', 'conversions', 'reports', 'multi_currency'],
            ],
            [
                'name' => 'cpx',
                'display_name' => 'CPX Network',
                'description' => 'CPX Affiliate Network - Performance marketing platform.',
                'logo_url' => '/images/networks/cpx-logo.png',
                'api_url' => 'https://api.cpx.ae/api/auth/conversions_report_dashboard',
                'auth_url' => 'https://dash.cpxaffiliate.com',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => ['affiliate_id' => '1634'],
                'api_settings' => [
                    'rate_limit' => 500,
                    'timeout' => 30,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['conversions', 'reports', 'dashboard'],
            ],
            [
                'name' => 'arabclicks',
                'display_name' => 'Arabclicks Network',
                'description' => 'MENA region affiliate network powered by HasOffers platform.',
                'logo_url' => '/images/networks/arabclicks-logo.png',
                'api_url' => 'https://arabclicks.api.hasoffers.com/Apiv3/json?Target=Affiliate_Report&Method=getConversions&page=1&limit=2000000&fields[]=Stat.offer_id&fields[]=Stat.datetime&fields[]=Offer.name&fields[]=Stat.conversion_status&fields[]=Stat.payout&fields[]=Stat.ad_id&fields[]=Stat.affiliate_info1&fields[]=Stat.affiliate_info5&sort[Stat.datetime]=desc&filters[Stat.date][conditional]=BETWEEN&hour_offset=-2&NetworkId=arabclicks&fields[]=Stat.conversion_sale_amount&',
                'auth_url' => 'https://arabclicks.com',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                    'network_id' => 'arabclicks',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['conversions', 'offers', 'stats', 'reports'],
            ],
            [
                'name' => 'globalnetwork',
                'display_name' => 'Global Network',
                'description' => 'International affiliate network powered by HasOffers platform.',
                'logo_url' => '/images/networks/globalnetwork-logo.png',
                'api_url' => 'https://globalnetwork1.api.hasoffers.com/Apiv3/json?Target=Affiliate_Report&Method=getConversions&page=1&limit=2000000&fields[]=Stat.offer_id&fields[]=Stat.datetime&fields[]=Offer.name&fields[]=Stat.conversion_status&fields[]=Stat.payout&fields[]=Stat.ad_id&fields[]=Stat.affiliate_info1&fields[]=Stat.affiliate_info5&sort[Stat.datetime]=desc&filters[Stat.date][conditional]=BETWEEN&hour_offset=5&fields[]=Stat.conversion_sale_amount&',
                'auth_url' => null,
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                    'network_id' => 'globalnetwork1',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['conversions', 'offers', 'stats', 'reports'],
            ],
            [
                'name' => 'linkaraby',
                'display_name' => 'Link Araby',
                'description' => 'MENA affiliate network - Data managed via Google Sheets.',
                'logo_url' => '/images/networks/linkaraby-logo.png',
                'api_url' => 'https://sheets.googleapis.com',
                'auth_url' => '',
                'callback_url' => '',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'data_source' => 'google_sheets',
                    'sheet_format' => 'yearly',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['manual_sync', 'google_sheets'],
            ],
            [
                'name' => 'icw',
                'display_name' => 'ICW Network',
                'description' => 'ICW Affiliate Network - Data managed via Google Sheets.',
                'logo_url' => '/images/networks/icw-logo.png',
                'api_url' => 'https://sheets.googleapis.com',
                'auth_url' => '',
                'callback_url' => '',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'data_source' => 'google_sheets',
                    'sheet_format' => 'monthly',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['manual_sync', 'google_sheets'],
            ],
            [
                'name' => 'globalemedia',
                'display_name' => 'Globalemedia Network',
                'description' => 'Performance marketing network with Trackier platform (HTML scraping).',
                'logo_url' => '/images/networks/globalemedia-logo.png',
                'api_url' => 'https://login.globalemedia.net/publisher/performance.html',
                'auth_url' => 'https://login.globalemedia.net',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 500,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                    'zone' => 'Asia/Dubai',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['performance', 'coupons', 'html_scraping'],
            ],
            [
                'name' => 'mediamak',
                'display_name' => 'MediaMak Network',
                'description' => 'Affiliate network - Data managed via Google Sheets.',
                'logo_url' => '/images/networks/mediamak-logo.png',
                'api_url' => 'https://sheets.googleapis.com',
                'auth_url' => '',
                'callback_url' => '',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'data_source' => 'google_sheets',
                    'sheet_format' => 'multi_sheet',
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['manual_sync', 'google_sheets'],
            ],
            [
                'name' => 'omolaat',
                'display_name' => 'Omolaat Network',
                'description' => 'MENA e-commerce network - Data via Chrome Extension with Arabic campaign name mapping.',
                'logo_url' => '/images/networks/omolaat-logo.png',
                'api_url' => 'https://api.omolaat.com',
                'auth_url' => '',
                'callback_url' => '',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [
                    'mapping_sheet_id' => '198PFR-xO0QESiCNuFvH84rLgZCqEPoWeB4uy8ysWlo4',
                ],
                'api_settings' => [
                    'data_source' => 'chrome_extension',
                    'aed_to_sar_rate' => 3.75,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['chrome_extension', 'arabic_names', 'google_sheets_mapping'],
            ],
            [
                'name' => 'marketeers',
                'display_name' => 'Marketeers Network',
                'description' => 'Performance marketing network with comprehensive coupon conversion tracking and reporting.',
                'logo_url' => '/images/networks/marketeers-logo.png',
                'api_url' => 'https://marketeers-backend-prod-oci.ollkom.com',
                'auth_url' => 'https://marketeers.ollkom.com',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'frontend_url' => 'https://marketeers.ollkom.com',
                    'backend_url' => 'https://marketeers-backend-prod-oci.ollkom.com',
                    'rate_limit' => 1000,
                    'timeout' => 30,
                    'retry_attempts' => 2,
                    'request_delay' => 0.1,
                    'verify_ssl' => false,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['coupon_conversions', 'campaigns', 'publisher_performance', 'reports', 'multi_currency'],
            ],
        ];

        foreach ($networks as $network) {
            Network::updateOrCreate(
                ['name' => $network['name']], // Find by name
                $network // Update with all data
            );
        }
    }
}