<?php

namespace Database\Seeders;

use App\Models\Network;
use Illuminate\Database\Seeder;

class NetworksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $networks = [
            [
                'name' => 'boostiny',
                'display_name' => 'Boostiny Network',
                'description' => 'Leading performance marketing network specializing in mobile apps and e-commerce.',
                'logo_url' => '/images/networks/boostiny-logo.png',
                'api_url' => 'https://api.boostiny.com/v2',
                'auth_url' => 'https://app.boostiny.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/boostiny',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 30,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['campaigns', 'link_performance', 'publisher_performance', 'reports'],
            ],
            [
                'name' => 'digizag',
                'display_name' => 'Digizag Network',
                'description' => 'Performance marketing network powered by HasOffers platform.',
                'logo_url' => '/images/networks/digizag-logo.png',
                'api_url' => 'https://digizag.api.hasoffers.com/Apiv3/json?Target=Affiliate_Report&Method=getConversions&page=1&limit=2000000&fields[]=Stat.offer_id&fields[]=Stat.datetime&fields[]=Offer.name&fields[]=Stat.conversion_status&fields[]=Stat.payout&fields[]=Stat.ad_id&fields[]=Stat.affiliate_info1&fields[]=Stat.affiliate_info5&sort[Stat.datetime]=desc&filters[Stat.date][conditional]=BETWEEN&hour_offset=5&fields[]=Stat.conversion_sale_amount&',
                'auth_url' => 'https://digizag.api.hasoffers.com',
                'callback_url' => null,
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['conversions', 'offers', 'stats', 'reports'],
            ],
            [
                'name' => 'ClickDealer',
                'display_name' => 'ClickDealer Network',
                'description' => 'Global affiliate network with diverse verticals and high-converting offers.',
                'logo_url' => '/images/networks/clickdealer-logo.png',
                'api_url' => 'https://api.clickdealer.com/v2',
                'auth_url' => 'https://affiliates.clickdealer.com/oauth',
                'callback_url' => 'https://yourdomain.com/callback/clickdealer',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 500,
                    'timeout' => 45,
                    'retry_attempts' => 5,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['offers', 'conversions', 'payouts', 'clicks'],
            ],
            [
                'name' => 'Admitad',
                'display_name' => 'Admitad Partner Network',
                'description' => 'International affiliate network with focus on e-commerce and retail.',
                'logo_url' => '/images/networks/admitad-logo.png',
                'api_url' => 'https://api.admitad.com/v1',
                'auth_url' => 'https://www.admitad.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/admitad',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 2000,
                    'timeout' => 60,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['programs', 'coupons', 'conversions', 'analytics'],
            ],
            [
                'name' => 'MaxBounty',
                'display_name' => 'MaxBounty Network',
                'description' => 'High-paying affiliate network with exclusive offers and dedicated support.',
                'logo_url' => '/images/networks/maxbounty-logo.png',
                'api_url' => 'https://api.maxbounty.com/v1',
                'auth_url' => 'https://www.maxbounty.com/oauth',
                'callback_url' => 'https://yourdomain.com/callback/maxbounty',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 800,
                    'timeout' => 30,
                    'retry_attempts' => 4,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['offers', 'conversions', 'payouts', 'support'],
            ],
            [
                'name' => 'PeerFly',
                'display_name' => 'PeerFly Affiliate Network',
                'description' => 'Performance marketing network with advanced tracking and optimization tools.',
                'logo_url' => '/images/networks/peerfly-logo.png',
                'api_url' => 'https://api.peerfly.com/v1',
                'auth_url' => 'https://peerfly.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/peerfly',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1200,
                    'timeout' => 40,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['campaigns', 'landing_pages', 'conversions', 'reports'],
            ],
            [
                'name' => 'CJ Affiliate',
                'display_name' => 'CJ Affiliate Network',
                'description' => 'Global affiliate marketing network with premium brands and advertisers.',
                'logo_url' => '/images/networks/cj-logo.png',
                'api_url' => 'https://api.cj.com/v3',
                'auth_url' => 'https://www.cj.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/cj',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 5000,
                    'timeout' => 60,
                    'retry_attempts' => 2,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['advertisers', 'products', 'links', 'reports'],
            ],
            [
                'name' => 'ShareASale',
                'display_name' => 'ShareASale Network',
                'description' => 'Affiliate network with extensive merchant base and user-friendly interface.',
                'logo_url' => '/images/networks/shareasale-logo.png',
                'api_url' => 'https://api.shareasale.com/v1',
                'auth_url' => 'https://www.shareasale.com/oauth',
                'callback_url' => 'https://yourdomain.com/callback/shareasale',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 1000,
                    'timeout' => 30,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['merchants', 'links', 'reports', 'payments'],
            ],
            [
                'name' => 'Awin',
                'display_name' => 'Awin Global Network',
                'description' => 'International affiliate network with advanced technology and global reach.',
                'logo_url' => '/images/networks/awin-logo.png',
                'api_url' => 'https://api.awin.com/v1',
                'auth_url' => 'https://www.awin.com/oauth/authorize',
                'callback_url' => 'https://yourdomain.com/callback/awin',
                'client_id' => null,
                'client_secret' => null,
                'contact_id' => null,
                'agency_id' => null,
                'credentials' => [],
                'api_settings' => [
                    'rate_limit' => 3000,
                    'timeout' => 45,
                    'retry_attempts' => 3,
                ],
                'is_active' => true,
                'is_connected' => false,
                'last_sync' => null,
                'supported_features' => ['advertisers', 'publishers', 'reports', 'analytics'],
            ],
        ];

        foreach ($networks as $network) {
            Network::updateOrCreate(
                ['name' => $network['name']], // Find by name
                $network // Update with all data
            );
        }
    }
}